repositories:
  - name: chatwork
    url: https://chatwork.github.io/charts
environments:
  '{{ .Environment.Name }}':
    values:
      - '../../config/environments/{{ .Environment.Name }}.yaml'
---
releases:
  - name: write-api-server-backend
    namespace: '{{ .Namespace | default "adceet" }}'
    labels:
      subsystem: write-api
      group: write-api-server
      role: backend
    chart: ../../charts/write-api-server
    version: '{{ .Values.writeApi.writeApiServer.backend.version }}'
    installedTemplate: '{{ .Values.writeApi.writeApiServer.backend.enabled }}'
    values:
      - values/settings.yaml.gotmpl