{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "akka.labels" . | nindent 4 }}
  name: "{{ include "akka.fullname" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "akka.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "akka.serviceAccountName" . }}"
    namespace: "{{ .Release.Namespace }}"
{{- end }}