{{- $root := . -}}
{{- range $name, $secret := .Values.secrets }}
{{- if eq (printf "%T" $secret) "string" }}
{{- if ne $secret "" }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "akka.labels" $root | nindent 4 }}
  name: "{{ template "akka.fullname" $root }}-{{ $name | replace "." "-" | lower }}"
data:
  {{ $name }}: {{ tpl $secret $root | b64enc | quote }}
{{- end }}

{{- else }}
{{- if $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "akka.labels" $root | nindent 4 }}
  name: "{{ template "akka.fullname" $root }}-{{ $name | replace "." "-" | lower }}"
data:
  {{- range $k, $v := $secret }}
  {{ $k }}: {{ tpl $v $root | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}