# See: https://doc.akka.io/docs/akka/current/discovery/index.html#discovery-method-aggregate-multiple-discovery-methods
akka:
  cluster:
    enabled: true
  discovery:
    enabled: true
    method: aggregate
    aggregate:
      discoveryMethods:
        - akka-dns
        - kubernetes-api
  management:
    enabled: true
    service:
      enabled: true
      clusterIP: None
  remote:
    enabled: true

replicaCount: 3

rbac:
  create: true

serviceAccount:
  create: true

podDisruptionBudget:
  enabled: false

autoscaling:
  enabled: false

metrics:
  enabled: false

useResourceApplicationConf: true