akka:
  http:
    enabled: true
    port: 8080
  discovery:
    enabled: true
  management:
    enabled: true
  remote:
    enabled: true

command:
  - /opt/docker/bin/akkavis
  - -Dconfig.resource=discovery-kubernetes.conf

env:
  - name: AKKAVIS_HOSTNAME
    value: "0.0.0.0"
  - name: AKKAVIS_PORT
    value: "8080"
  - name: AKKA_DISCOVERY_KUBERNETES_API_POD_NAMESPACE
    value: "akka"
  - name: AKKA_DISCOVERY_KUBERNETES_API_POD_LABEL_SELECTOR
    value: "app.kubernetes.io/instance=%s"
  - name: AKKA_MANAGEMENT_CLUSTER_BOOTSTRAP_CONNTACT_POINT_DISCOVERY_SERVICE_NAME
    value: "akka-use-environment-variable-and-secret"
  - name: ENV
    valueFrom:
      configMapKeyRef:
        name: akka-use-environment-variable-and-secret-env
        key: ENV
  - name: SECRET
    valueFrom:
      secretKeyRef:
        name: akka-use-environment-variable-and-secret-env
        key: SECRET

envFrom:
  - configMapRef:
      name: akka-use-environment-variable-and-secret-envfrom

replicaCount: 3

rbac:
  create: true

serviceAccount:
  create: true

podDisruptionBudget:
  enabled: false

autoscaling:
  enabled: false

metrics:
  enabled: false

useResourceApplicationConf: false
configmaps:
  chart.conf: ""
  akka.conf: ""
  kamon.conf: ""
  env:
    ENV: "xxxx"
  envFrom:
    ENV1: "1"
    ENV2: "2"
    ENV3: "3"

secrets:
  env:
    SECRET: "xxxx"
