name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.scala'
      - '**.kt'
      - '**.sbt'
      - '.scalafmt.conf'
      - 'project/build.properties'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - '**.scala'
      - '**.kt'
      - '**.sbt'
      - '.scalafmt.conf'
      - 'project/build.properties'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M --enable-preview -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M --enable-preview -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - run: sbt -v lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M --enable-preview -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M --enable-preview -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - name: sbt test
        run: sbt -v test
  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'j5ik2o-bot[bot]'
    needs: test
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 111016
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_FILTER_AUTHOR: "j5ik2o-bot[bot]"
          MERGE_DELETE_BRANCH: "true"
